#!/bin/bash

CURRENT_DIRECTORY=$(pwd | grep -o '[^/]*$')
if [ "$CURRENT_DIRECTORY" == "developer-tools" ] ; then
	cd ..
fi

latest_hash_of_package_json="$(git log --pretty=format:%H developer-tools/package.json | head -1)"
latest_saved_hash=""

cd developer-tools

need_npm_i=false

if [[ -f latest_hash_of_package_json && -d node_modules ]]; then
	latest_saved_hash="$(cat latest_hash_of_package_json | head -1)"
	if [ "$latest_saved_hash" == "$latest_hash_of_package_json" ]; then
		echo "doesn't need npm i"
		need_npm_i=false
	else
		echo "package.json is changed, need npm i"
		need_npm_i=true
	fi
else
	echo "initial run"
	need_npm_i=true
fi

error=false
if $need_npm_i ; then
	echo "running the npm install..."
	npm set progress=false
	npm i
	OUT=$?
	if [ $OUT -eq 0 ]; then
		echo "${latest_hash_of_package_json}" > latest_hash_of_package_json
	else
		error=true
	fi
fi

./node_modules/.bin/gulp --silent --gulpfile gulpfile-pug.js
if [ $? -ne 0 ] ; then
	error=true
fi
./node_modules/.bin/gulp --silent --gulpfile gulpfile-favicon.js
if [ $? -ne 0 ] ; then
	error=true
fi
./node_modules/.bin/webpack
if [ $? -ne 0 ] ; then
	error=true
fi

if $error ; then
	exit -1
else
	echo "application available in 'dist/progbot.html'"
fi
