#!/bin/sh
echo
echo "**********************"
echo "* sarkiroka miniprog *"
echo "**********************"
echo
if [ $# -ne 0 ] ; then
    echo "Error: \"$1\" not available in this project"
    echo ""
fi
echo "Available commands:"
echo "    ./run                 - build the application"
echo "    ./run build           - build the application"
echo "    ./run dev             - build & watch"
echo "    ./run help            - shows this help"
echo ""
